/* eslint-disable quotes */
export default {
  status: 200,
  userid: {
    name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Name",
      translate: false,
      trim: true
    },
    display_name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["is_company", "name", "parent_id.display_name", "type", "company_name", "name"],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Display Name",
      translate: false,
      trim: true
    },
    date: {
      type: "date",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Date"
    },
    title: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.partner.title",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Title"
    },
    parent_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.partner",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Related Company"
    },
    parent_name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["parent_id.name"],
      manual: false,
      readonly: true,
      related: ["parent_id", "name"],
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Parent name",
      translate: false,
      trim: true
    },
    child_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["child_ids.active"],
      domain: [["active", "=", true]],
      manual: false,
      readonly: false,
      relation: "res.partner",
      relation_field: "parent_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Contact"
    },
    ref: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Reference",
      translate: false,
      trim: true
    },
    lang: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "All the emails and documents sent to this contact will be translated in this language.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [["en_US", "English (US)"]],
      sortable: true,
      store: true,
      string: "Language"
    },
    active_lang_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: ["lang"],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Active Lang Count"
    },
    tz: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "When printing documents and exporting/importing data, time values are computed according to this timezone.\nIf the timezone is not set, UTC (Coordinated Universal Time) is used.\nAnywhere else, time values are computed according to the time offset of your web client.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [
        ["Africa/Abidjan", "Africa/Abidjan"],
        ["Africa/Accra", "Africa/Accra"],
        ["Africa/Addis_Ababa", "Africa/Addis_Ababa"],
        ["Africa/Algiers", "Africa/Algiers"],
        ["Africa/Asmara", "Africa/Asmara"],
        ["Africa/Asmera", "Africa/Asmera"],
        ["Africa/Bamako", "Africa/Bamako"],
        ["Africa/Bangui", "Africa/Bangui"],
        ["Africa/Banjul", "Africa/Banjul"],
        ["Africa/Bissau", "Africa/Bissau"],
        ["Africa/Blantyre", "Africa/Blantyre"],
        ["Africa/Brazzaville", "Africa/Brazzaville"],
        ["Africa/Bujumbura", "Africa/Bujumbura"],
        ["Africa/Cairo", "Africa/Cairo"],
        ["Africa/Casablanca", "Africa/Casablanca"],
        ["Africa/Ceuta", "Africa/Ceuta"],
        ["Africa/Conakry", "Africa/Conakry"],
        ["Africa/Dakar", "Africa/Dakar"],
        ["Africa/Dar_es_Salaam", "Africa/Dar_es_Salaam"],
        ["Africa/Djibouti", "Africa/Djibouti"],
        ["Africa/Douala", "Africa/Douala"],
        ["Africa/El_Aaiun", "Africa/El_Aaiun"],
        ["Africa/Freetown", "Africa/Freetown"],
        ["Africa/Gaborone", "Africa/Gaborone"],
        ["Africa/Harare", "Africa/Harare"],
        ["Africa/Johannesburg", "Africa/Johannesburg"],
        ["Africa/Juba", "Africa/Juba"],
        ["Africa/Kampala", "Africa/Kampala"],
        ["Africa/Khartoum", "Africa/Khartoum"],
        ["Africa/Kigali", "Africa/Kigali"],
        ["Africa/Kinshasa", "Africa/Kinshasa"],
        ["Africa/Lagos", "Africa/Lagos"],
        ["Africa/Libreville", "Africa/Libreville"],
        ["Africa/Lome", "Africa/Lome"],
        ["Africa/Luanda", "Africa/Luanda"],
        ["Africa/Lubumbashi", "Africa/Lubumbashi"],
        ["Africa/Lusaka", "Africa/Lusaka"],
        ["Africa/Malabo", "Africa/Malabo"],
        ["Africa/Maputo", "Africa/Maputo"],
        ["Africa/Maseru", "Africa/Maseru"],
        ["Africa/Mbabane", "Africa/Mbabane"],
        ["Africa/Mogadishu", "Africa/Mogadishu"],
        ["Africa/Monrovia", "Africa/Monrovia"],
        ["Africa/Nairobi", "Africa/Nairobi"],
        ["Africa/Ndjamena", "Africa/Ndjamena"],
        ["Africa/Niamey", "Africa/Niamey"],
        ["Africa/Nouakchott", "Africa/Nouakchott"],
        ["Africa/Ouagadougou", "Africa/Ouagadougou"],
        ["Africa/Porto-Novo", "Africa/Porto-Novo"],
        ["Africa/Sao_Tome", "Africa/Sao_Tome"],
        ["Africa/Timbuktu", "Africa/Timbuktu"],
        ["Africa/Tripoli", "Africa/Tripoli"],
        ["Africa/Tunis", "Africa/Tunis"],
        ["Africa/Windhoek", "Africa/Windhoek"],
        ["America/Adak", "America/Adak"],
        ["America/Anchorage", "America/Anchorage"],
        ["America/Anguilla", "America/Anguilla"],
        ["America/Antigua", "America/Antigua"],
        ["America/Araguaina", "America/Araguaina"],
        ["America/Argentina/Buenos_Aires", "America/Argentina/Buenos_Aires"],
        ["America/Argentina/Catamarca", "America/Argentina/Catamarca"],
        ["America/Argentina/ComodRivadavia", "America/Argentina/ComodRivadavia"],
        ["America/Argentina/Cordoba", "America/Argentina/Cordoba"],
        ["America/Argentina/Jujuy", "America/Argentina/Jujuy"],
        ["America/Argentina/La_Rioja", "America/Argentina/La_Rioja"],
        ["America/Argentina/Mendoza", "America/Argentina/Mendoza"],
        ["America/Argentina/Rio_Gallegos", "America/Argentina/Rio_Gallegos"],
        ["America/Argentina/Salta", "America/Argentina/Salta"],
        ["America/Argentina/San_Juan", "America/Argentina/San_Juan"],
        ["America/Argentina/San_Luis", "America/Argentina/San_Luis"],
        ["America/Argentina/Tucuman", "America/Argentina/Tucuman"],
        ["America/Argentina/Ushuaia", "America/Argentina/Ushuaia"],
        ["America/Aruba", "America/Aruba"],
        ["America/Asuncion", "America/Asuncion"],
        ["America/Atikokan", "America/Atikokan"],
        ["America/Atka", "America/Atka"],
        ["America/Bahia", "America/Bahia"],
        ["America/Bahia_Banderas", "America/Bahia_Banderas"],
        ["America/Barbados", "America/Barbados"],
        ["America/Belem", "America/Belem"],
        ["America/Belize", "America/Belize"],
        ["America/Blanc-Sablon", "America/Blanc-Sablon"],
        ["America/Boa_Vista", "America/Boa_Vista"],
        ["America/Bogota", "America/Bogota"],
        ["America/Boise", "America/Boise"],
        ["America/Buenos_Aires", "America/Buenos_Aires"],
        ["America/Cambridge_Bay", "America/Cambridge_Bay"],
        ["America/Campo_Grande", "America/Campo_Grande"],
        ["America/Cancun", "America/Cancun"],
        ["America/Caracas", "America/Caracas"],
        ["America/Catamarca", "America/Catamarca"],
        ["America/Cayenne", "America/Cayenne"],
        ["America/Cayman", "America/Cayman"],
        ["America/Chicago", "America/Chicago"],
        ["America/Chihuahua", "America/Chihuahua"],
        ["America/Coral_Harbour", "America/Coral_Harbour"],
        ["America/Cordoba", "America/Cordoba"],
        ["America/Costa_Rica", "America/Costa_Rica"],
        ["America/Creston", "America/Creston"],
        ["America/Cuiaba", "America/Cuiaba"],
        ["America/Curacao", "America/Curacao"],
        ["America/Danmarkshavn", "America/Danmarkshavn"],
        ["America/Dawson", "America/Dawson"],
        ["America/Dawson_Creek", "America/Dawson_Creek"],
        ["America/Denver", "America/Denver"],
        ["America/Detroit", "America/Detroit"],
        ["America/Dominica", "America/Dominica"],
        ["America/Edmonton", "America/Edmonton"],
        ["America/Eirunepe", "America/Eirunepe"],
        ["America/El_Salvador", "America/El_Salvador"],
        ["America/Ensenada", "America/Ensenada"],
        ["America/Fort_Nelson", "America/Fort_Nelson"],
        ["America/Fort_Wayne", "America/Fort_Wayne"],
        ["America/Fortaleza", "America/Fortaleza"],
        ["America/Glace_Bay", "America/Glace_Bay"],
        ["America/Godthab", "America/Godthab"],
        ["America/Goose_Bay", "America/Goose_Bay"],
        ["America/Grand_Turk", "America/Grand_Turk"],
        ["America/Grenada", "America/Grenada"],
        ["America/Guadeloupe", "America/Guadeloupe"],
        ["America/Guatemala", "America/Guatemala"],
        ["America/Guayaquil", "America/Guayaquil"],
        ["America/Guyana", "America/Guyana"],
        ["America/Halifax", "America/Halifax"],
        ["America/Havana", "America/Havana"],
        ["America/Hermosillo", "America/Hermosillo"],
        ["America/Indiana/Indianapolis", "America/Indiana/Indianapolis"],
        ["America/Indiana/Knox", "America/Indiana/Knox"],
        ["America/Indiana/Marengo", "America/Indiana/Marengo"],
        ["America/Indiana/Petersburg", "America/Indiana/Petersburg"],
        ["America/Indiana/Tell_City", "America/Indiana/Tell_City"],
        ["America/Indiana/Vevay", "America/Indiana/Vevay"],
        ["America/Indiana/Vincennes", "America/Indiana/Vincennes"],
        ["America/Indiana/Winamac", "America/Indiana/Winamac"],
        ["America/Indianapolis", "America/Indianapolis"],
        ["America/Inuvik", "America/Inuvik"],
        ["America/Iqaluit", "America/Iqaluit"],
        ["America/Jamaica", "America/Jamaica"],
        ["America/Jujuy", "America/Jujuy"],
        ["America/Juneau", "America/Juneau"],
        ["America/Kentucky/Louisville", "America/Kentucky/Louisville"],
        ["America/Kentucky/Monticello", "America/Kentucky/Monticello"],
        ["America/Knox_IN", "America/Knox_IN"],
        ["America/Kralendijk", "America/Kralendijk"],
        ["America/La_Paz", "America/La_Paz"],
        ["America/Lima", "America/Lima"],
        ["America/Los_Angeles", "America/Los_Angeles"],
        ["America/Louisville", "America/Louisville"],
        ["America/Lower_Princes", "America/Lower_Princes"],
        ["America/Maceio", "America/Maceio"],
        ["America/Managua", "America/Managua"],
        ["America/Manaus", "America/Manaus"],
        ["America/Marigot", "America/Marigot"],
        ["America/Martinique", "America/Martinique"],
        ["America/Matamoros", "America/Matamoros"],
        ["America/Mazatlan", "America/Mazatlan"],
        ["America/Mendoza", "America/Mendoza"],
        ["America/Menominee", "America/Menominee"],
        ["America/Merida", "America/Merida"],
        ["America/Metlakatla", "America/Metlakatla"],
        ["America/Mexico_City", "America/Mexico_City"],
        ["America/Miquelon", "America/Miquelon"],
        ["America/Moncton", "America/Moncton"],
        ["America/Monterrey", "America/Monterrey"],
        ["America/Montevideo", "America/Montevideo"],
        ["America/Montreal", "America/Montreal"],
        ["America/Montserrat", "America/Montserrat"],
        ["America/Nassau", "America/Nassau"],
        ["America/New_York", "America/New_York"],
        ["America/Nipigon", "America/Nipigon"],
        ["America/Nome", "America/Nome"],
        ["America/Noronha", "America/Noronha"],
        ["America/North_Dakota/Beulah", "America/North_Dakota/Beulah"],
        ["America/North_Dakota/Center", "America/North_Dakota/Center"],
        ["America/North_Dakota/New_Salem", "America/North_Dakota/New_Salem"],
        ["America/Ojinaga", "America/Ojinaga"],
        ["America/Panama", "America/Panama"],
        ["America/Pangnirtung", "America/Pangnirtung"],
        ["America/Paramaribo", "America/Paramaribo"],
        ["America/Phoenix", "America/Phoenix"],
        ["America/Port-au-Prince", "America/Port-au-Prince"],
        ["America/Port_of_Spain", "America/Port_of_Spain"],
        ["America/Porto_Acre", "America/Porto_Acre"],
        ["America/Porto_Velho", "America/Porto_Velho"],
        ["America/Puerto_Rico", "America/Puerto_Rico"],
        ["America/Punta_Arenas", "America/Punta_Arenas"],
        ["America/Rainy_River", "America/Rainy_River"],
        ["America/Rankin_Inlet", "America/Rankin_Inlet"],
        ["America/Recife", "America/Recife"],
        ["America/Regina", "America/Regina"],
        ["America/Resolute", "America/Resolute"],
        ["America/Rio_Branco", "America/Rio_Branco"],
        ["America/Rosario", "America/Rosario"],
        ["America/Santa_Isabel", "America/Santa_Isabel"],
        ["America/Santarem", "America/Santarem"],
        ["America/Santiago", "America/Santiago"],
        ["America/Santo_Domingo", "America/Santo_Domingo"],
        ["America/Sao_Paulo", "America/Sao_Paulo"],
        ["America/Scoresbysund", "America/Scoresbysund"],
        ["America/Shiprock", "America/Shiprock"],
        ["America/Sitka", "America/Sitka"],
        ["America/St_Barthelemy", "America/St_Barthelemy"],
        ["America/St_Johns", "America/St_Johns"],
        ["America/St_Kitts", "America/St_Kitts"],
        ["America/St_Lucia", "America/St_Lucia"],
        ["America/St_Thomas", "America/St_Thomas"],
        ["America/St_Vincent", "America/St_Vincent"],
        ["America/Swift_Current", "America/Swift_Current"],
        ["America/Tegucigalpa", "America/Tegucigalpa"],
        ["America/Thule", "America/Thule"],
        ["America/Thunder_Bay", "America/Thunder_Bay"],
        ["America/Tijuana", "America/Tijuana"],
        ["America/Toronto", "America/Toronto"],
        ["America/Tortola", "America/Tortola"],
        ["America/Vancouver", "America/Vancouver"],
        ["America/Virgin", "America/Virgin"],
        ["America/Whitehorse", "America/Whitehorse"],
        ["America/Winnipeg", "America/Winnipeg"],
        ["America/Yakutat", "America/Yakutat"],
        ["America/Yellowknife", "America/Yellowknife"],
        ["Antarctica/Casey", "Antarctica/Casey"],
        ["Antarctica/Davis", "Antarctica/Davis"],
        ["Antarctica/DumontDUrville", "Antarctica/DumontDUrville"],
        ["Antarctica/Macquarie", "Antarctica/Macquarie"],
        ["Antarctica/Mawson", "Antarctica/Mawson"],
        ["Antarctica/McMurdo", "Antarctica/McMurdo"],
        ["Antarctica/Palmer", "Antarctica/Palmer"],
        ["Antarctica/Rothera", "Antarctica/Rothera"],
        ["Antarctica/South_Pole", "Antarctica/South_Pole"],
        ["Antarctica/Syowa", "Antarctica/Syowa"],
        ["Antarctica/Troll", "Antarctica/Troll"],
        ["Antarctica/Vostok", "Antarctica/Vostok"],
        ["Arctic/Longyearbyen", "Arctic/Longyearbyen"],
        ["Asia/Aden", "Asia/Aden"],
        ["Asia/Almaty", "Asia/Almaty"],
        ["Asia/Amman", "Asia/Amman"],
        ["Asia/Anadyr", "Asia/Anadyr"],
        ["Asia/Aqtau", "Asia/Aqtau"],
        ["Asia/Aqtobe", "Asia/Aqtobe"],
        ["Asia/Ashgabat", "Asia/Ashgabat"],
        ["Asia/Ashkhabad", "Asia/Ashkhabad"],
        ["Asia/Atyrau", "Asia/Atyrau"],
        ["Asia/Baghdad", "Asia/Baghdad"],
        ["Asia/Bahrain", "Asia/Bahrain"],
        ["Asia/Baku", "Asia/Baku"],
        ["Asia/Bangkok", "Asia/Bangkok"],
        ["Asia/Barnaul", "Asia/Barnaul"],
        ["Asia/Beirut", "Asia/Beirut"],
        ["Asia/Bishkek", "Asia/Bishkek"],
        ["Asia/Brunei", "Asia/Brunei"],
        ["Asia/Calcutta", "Asia/Calcutta"],
        ["Asia/Chita", "Asia/Chita"],
        ["Asia/Choibalsan", "Asia/Choibalsan"],
        ["Asia/Chongqing", "Asia/Chongqing"],
        ["Asia/Chungking", "Asia/Chungking"],
        ["Asia/Colombo", "Asia/Colombo"],
        ["Asia/Dacca", "Asia/Dacca"],
        ["Asia/Damascus", "Asia/Damascus"],
        ["Asia/Dhaka", "Asia/Dhaka"],
        ["Asia/Dili", "Asia/Dili"],
        ["Asia/Dubai", "Asia/Dubai"],
        ["Asia/Dushanbe", "Asia/Dushanbe"],
        ["Asia/Famagusta", "Asia/Famagusta"],
        ["Asia/Gaza", "Asia/Gaza"],
        ["Asia/Harbin", "Asia/Harbin"],
        ["Asia/Hebron", "Asia/Hebron"],
        ["Asia/Ho_Chi_Minh", "Asia/Ho_Chi_Minh"],
        ["Asia/Hong_Kong", "Asia/Hong_Kong"],
        ["Asia/Hovd", "Asia/Hovd"],
        ["Asia/Irkutsk", "Asia/Irkutsk"],
        ["Asia/Istanbul", "Asia/Istanbul"],
        ["Asia/Jakarta", "Asia/Jakarta"],
        ["Asia/Jayapura", "Asia/Jayapura"],
        ["Asia/Jerusalem", "Asia/Jerusalem"],
        ["Asia/Kabul", "Asia/Kabul"],
        ["Asia/Kamchatka", "Asia/Kamchatka"],
        ["Asia/Karachi", "Asia/Karachi"],
        ["Asia/Kashgar", "Asia/Kashgar"],
        ["Asia/Kathmandu", "Asia/Kathmandu"],
        ["Asia/Katmandu", "Asia/Katmandu"],
        ["Asia/Khandyga", "Asia/Khandyga"],
        ["Asia/Kolkata", "Asia/Kolkata"],
        ["Asia/Krasnoyarsk", "Asia/Krasnoyarsk"],
        ["Asia/Kuala_Lumpur", "Asia/Kuala_Lumpur"],
        ["Asia/Kuching", "Asia/Kuching"],
        ["Asia/Kuwait", "Asia/Kuwait"],
        ["Asia/Macao", "Asia/Macao"],
        ["Asia/Macau", "Asia/Macau"],
        ["Asia/Magadan", "Asia/Magadan"],
        ["Asia/Makassar", "Asia/Makassar"],
        ["Asia/Manila", "Asia/Manila"],
        ["Asia/Muscat", "Asia/Muscat"],
        ["Asia/Nicosia", "Asia/Nicosia"],
        ["Asia/Novokuznetsk", "Asia/Novokuznetsk"],
        ["Asia/Novosibirsk", "Asia/Novosibirsk"],
        ["Asia/Omsk", "Asia/Omsk"],
        ["Asia/Oral", "Asia/Oral"],
        ["Asia/Phnom_Penh", "Asia/Phnom_Penh"],
        ["Asia/Pontianak", "Asia/Pontianak"],
        ["Asia/Pyongyang", "Asia/Pyongyang"],
        ["Asia/Qatar", "Asia/Qatar"],
        ["Asia/Qostanay", "Asia/Qostanay"],
        ["Asia/Qyzylorda", "Asia/Qyzylorda"],
        ["Asia/Rangoon", "Asia/Rangoon"],
        ["Asia/Riyadh", "Asia/Riyadh"],
        ["Asia/Saigon", "Asia/Saigon"],
        ["Asia/Sakhalin", "Asia/Sakhalin"],
        ["Asia/Samarkand", "Asia/Samarkand"],
        ["Asia/Seoul", "Asia/Seoul"],
        ["Asia/Shanghai", "Asia/Shanghai"],
        ["Asia/Singapore", "Asia/Singapore"],
        ["Asia/Srednekolymsk", "Asia/Srednekolymsk"],
        ["Asia/Taipei", "Asia/Taipei"],
        ["Asia/Tashkent", "Asia/Tashkent"],
        ["Asia/Tbilisi", "Asia/Tbilisi"],
        ["Asia/Tehran", "Asia/Tehran"],
        ["Asia/Tel_Aviv", "Asia/Tel_Aviv"],
        ["Asia/Thimbu", "Asia/Thimbu"],
        ["Asia/Thimphu", "Asia/Thimphu"],
        ["Asia/Tokyo", "Asia/Tokyo"],
        ["Asia/Tomsk", "Asia/Tomsk"],
        ["Asia/Ujung_Pandang", "Asia/Ujung_Pandang"],
        ["Asia/Ulaanbaatar", "Asia/Ulaanbaatar"],
        ["Asia/Ulan_Bator", "Asia/Ulan_Bator"],
        ["Asia/Urumqi", "Asia/Urumqi"],
        ["Asia/Ust-Nera", "Asia/Ust-Nera"],
        ["Asia/Vientiane", "Asia/Vientiane"],
        ["Asia/Vladivostok", "Asia/Vladivostok"],
        ["Asia/Yakutsk", "Asia/Yakutsk"],
        ["Asia/Yangon", "Asia/Yangon"],
        ["Asia/Yekaterinburg", "Asia/Yekaterinburg"],
        ["Asia/Yerevan", "Asia/Yerevan"],
        ["Atlantic/Azores", "Atlantic/Azores"],
        ["Atlantic/Bermuda", "Atlantic/Bermuda"],
        ["Atlantic/Canary", "Atlantic/Canary"],
        ["Atlantic/Cape_Verde", "Atlantic/Cape_Verde"],
        ["Atlantic/Faeroe", "Atlantic/Faeroe"],
        ["Atlantic/Faroe", "Atlantic/Faroe"],
        ["Atlantic/Jan_Mayen", "Atlantic/Jan_Mayen"],
        ["Atlantic/Madeira", "Atlantic/Madeira"],
        ["Atlantic/Reykjavik", "Atlantic/Reykjavik"],
        ["Atlantic/South_Georgia", "Atlantic/South_Georgia"],
        ["Atlantic/St_Helena", "Atlantic/St_Helena"],
        ["Atlantic/Stanley", "Atlantic/Stanley"],
        ["Australia/ACT", "Australia/ACT"],
        ["Australia/Adelaide", "Australia/Adelaide"],
        ["Australia/Brisbane", "Australia/Brisbane"],
        ["Australia/Broken_Hill", "Australia/Broken_Hill"],
        ["Australia/Canberra", "Australia/Canberra"],
        ["Australia/Currie", "Australia/Currie"],
        ["Australia/Darwin", "Australia/Darwin"],
        ["Australia/Eucla", "Australia/Eucla"],
        ["Australia/Hobart", "Australia/Hobart"],
        ["Australia/LHI", "Australia/LHI"],
        ["Australia/Lindeman", "Australia/Lindeman"],
        ["Australia/Lord_Howe", "Australia/Lord_Howe"],
        ["Australia/Melbourne", "Australia/Melbourne"],
        ["Australia/NSW", "Australia/NSW"],
        ["Australia/North", "Australia/North"],
        ["Australia/Perth", "Australia/Perth"],
        ["Australia/Queensland", "Australia/Queensland"],
        ["Australia/South", "Australia/South"],
        ["Australia/Sydney", "Australia/Sydney"],
        ["Australia/Tasmania", "Australia/Tasmania"],
        ["Australia/Victoria", "Australia/Victoria"],
        ["Australia/West", "Australia/West"],
        ["Australia/Yancowinna", "Australia/Yancowinna"],
        ["Brazil/Acre", "Brazil/Acre"],
        ["Brazil/DeNoronha", "Brazil/DeNoronha"],
        ["Brazil/East", "Brazil/East"],
        ["Brazil/West", "Brazil/West"],
        ["CET", "CET"],
        ["CST6CDT", "CST6CDT"],
        ["Canada/Atlantic", "Canada/Atlantic"],
        ["Canada/Central", "Canada/Central"],
        ["Canada/Eastern", "Canada/Eastern"],
        ["Canada/Mountain", "Canada/Mountain"],
        ["Canada/Newfoundland", "Canada/Newfoundland"],
        ["Canada/Pacific", "Canada/Pacific"],
        ["Canada/Saskatchewan", "Canada/Saskatchewan"],
        ["Canada/Yukon", "Canada/Yukon"],
        ["Chile/Continental", "Chile/Continental"],
        ["Chile/EasterIsland", "Chile/EasterIsland"],
        ["Cuba", "Cuba"],
        ["EET", "EET"],
        ["EST", "EST"],
        ["EST5EDT", "EST5EDT"],
        ["Egypt", "Egypt"],
        ["Eire", "Eire"],
        ["Europe/Amsterdam", "Europe/Amsterdam"],
        ["Europe/Andorra", "Europe/Andorra"],
        ["Europe/Astrakhan", "Europe/Astrakhan"],
        ["Europe/Athens", "Europe/Athens"],
        ["Europe/Belfast", "Europe/Belfast"],
        ["Europe/Belgrade", "Europe/Belgrade"],
        ["Europe/Berlin", "Europe/Berlin"],
        ["Europe/Bratislava", "Europe/Bratislava"],
        ["Europe/Brussels", "Europe/Brussels"],
        ["Europe/Bucharest", "Europe/Bucharest"],
        ["Europe/Budapest", "Europe/Budapest"],
        ["Europe/Busingen", "Europe/Busingen"],
        ["Europe/Chisinau", "Europe/Chisinau"],
        ["Europe/Copenhagen", "Europe/Copenhagen"],
        ["Europe/Dublin", "Europe/Dublin"],
        ["Europe/Gibraltar", "Europe/Gibraltar"],
        ["Europe/Guernsey", "Europe/Guernsey"],
        ["Europe/Helsinki", "Europe/Helsinki"],
        ["Europe/Isle_of_Man", "Europe/Isle_of_Man"],
        ["Europe/Istanbul", "Europe/Istanbul"],
        ["Europe/Jersey", "Europe/Jersey"],
        ["Europe/Kaliningrad", "Europe/Kaliningrad"],
        ["Europe/Kiev", "Europe/Kiev"],
        ["Europe/Kirov", "Europe/Kirov"],
        ["Europe/Lisbon", "Europe/Lisbon"],
        ["Europe/Ljubljana", "Europe/Ljubljana"],
        ["Europe/London", "Europe/London"],
        ["Europe/Luxembourg", "Europe/Luxembourg"],
        ["Europe/Madrid", "Europe/Madrid"],
        ["Europe/Malta", "Europe/Malta"],
        ["Europe/Mariehamn", "Europe/Mariehamn"],
        ["Europe/Minsk", "Europe/Minsk"],
        ["Europe/Monaco", "Europe/Monaco"],
        ["Europe/Moscow", "Europe/Moscow"],
        ["Europe/Nicosia", "Europe/Nicosia"],
        ["Europe/Oslo", "Europe/Oslo"],
        ["Europe/Paris", "Europe/Paris"],
        ["Europe/Podgorica", "Europe/Podgorica"],
        ["Europe/Prague", "Europe/Prague"],
        ["Europe/Riga", "Europe/Riga"],
        ["Europe/Rome", "Europe/Rome"],
        ["Europe/Samara", "Europe/Samara"],
        ["Europe/San_Marino", "Europe/San_Marino"],
        ["Europe/Sarajevo", "Europe/Sarajevo"],
        ["Europe/Saratov", "Europe/Saratov"],
        ["Europe/Simferopol", "Europe/Simferopol"],
        ["Europe/Skopje", "Europe/Skopje"],
        ["Europe/Sofia", "Europe/Sofia"],
        ["Europe/Stockholm", "Europe/Stockholm"],
        ["Europe/Tallinn", "Europe/Tallinn"],
        ["Europe/Tirane", "Europe/Tirane"],
        ["Europe/Tiraspol", "Europe/Tiraspol"],
        ["Europe/Ulyanovsk", "Europe/Ulyanovsk"],
        ["Europe/Uzhgorod", "Europe/Uzhgorod"],
        ["Europe/Vaduz", "Europe/Vaduz"],
        ["Europe/Vatican", "Europe/Vatican"],
        ["Europe/Vienna", "Europe/Vienna"],
        ["Europe/Vilnius", "Europe/Vilnius"],
        ["Europe/Volgograd", "Europe/Volgograd"],
        ["Europe/Warsaw", "Europe/Warsaw"],
        ["Europe/Zagreb", "Europe/Zagreb"],
        ["Europe/Zaporozhye", "Europe/Zaporozhye"],
        ["Europe/Zurich", "Europe/Zurich"],
        ["GB", "GB"],
        ["GB-Eire", "GB-Eire"],
        ["GMT", "GMT"],
        ["GMT+0", "GMT+0"],
        ["GMT-0", "GMT-0"],
        ["GMT0", "GMT0"],
        ["Greenwich", "Greenwich"],
        ["HST", "HST"],
        ["Hongkong", "Hongkong"],
        ["Iceland", "Iceland"],
        ["Indian/Antananarivo", "Indian/Antananarivo"],
        ["Indian/Chagos", "Indian/Chagos"],
        ["Indian/Christmas", "Indian/Christmas"],
        ["Indian/Cocos", "Indian/Cocos"],
        ["Indian/Comoro", "Indian/Comoro"],
        ["Indian/Kerguelen", "Indian/Kerguelen"],
        ["Indian/Mahe", "Indian/Mahe"],
        ["Indian/Maldives", "Indian/Maldives"],
        ["Indian/Mauritius", "Indian/Mauritius"],
        ["Indian/Mayotte", "Indian/Mayotte"],
        ["Indian/Reunion", "Indian/Reunion"],
        ["Iran", "Iran"],
        ["Israel", "Israel"],
        ["Jamaica", "Jamaica"],
        ["Japan", "Japan"],
        ["Kwajalein", "Kwajalein"],
        ["Libya", "Libya"],
        ["MET", "MET"],
        ["MST", "MST"],
        ["MST7MDT", "MST7MDT"],
        ["Mexico/BajaNorte", "Mexico/BajaNorte"],
        ["Mexico/BajaSur", "Mexico/BajaSur"],
        ["Mexico/General", "Mexico/General"],
        ["NZ", "NZ"],
        ["NZ-CHAT", "NZ-CHAT"],
        ["Navajo", "Navajo"],
        ["PRC", "PRC"],
        ["PST8PDT", "PST8PDT"],
        ["Pacific/Apia", "Pacific/Apia"],
        ["Pacific/Auckland", "Pacific/Auckland"],
        ["Pacific/Bougainville", "Pacific/Bougainville"],
        ["Pacific/Chatham", "Pacific/Chatham"],
        ["Pacific/Chuuk", "Pacific/Chuuk"],
        ["Pacific/Easter", "Pacific/Easter"],
        ["Pacific/Efate", "Pacific/Efate"],
        ["Pacific/Enderbury", "Pacific/Enderbury"],
        ["Pacific/Fakaofo", "Pacific/Fakaofo"],
        ["Pacific/Fiji", "Pacific/Fiji"],
        ["Pacific/Funafuti", "Pacific/Funafuti"],
        ["Pacific/Galapagos", "Pacific/Galapagos"],
        ["Pacific/Gambier", "Pacific/Gambier"],
        ["Pacific/Guadalcanal", "Pacific/Guadalcanal"],
        ["Pacific/Guam", "Pacific/Guam"],
        ["Pacific/Honolulu", "Pacific/Honolulu"],
        ["Pacific/Johnston", "Pacific/Johnston"],
        ["Pacific/Kiritimati", "Pacific/Kiritimati"],
        ["Pacific/Kosrae", "Pacific/Kosrae"],
        ["Pacific/Kwajalein", "Pacific/Kwajalein"],
        ["Pacific/Majuro", "Pacific/Majuro"],
        ["Pacific/Marquesas", "Pacific/Marquesas"],
        ["Pacific/Midway", "Pacific/Midway"],
        ["Pacific/Nauru", "Pacific/Nauru"],
        ["Pacific/Niue", "Pacific/Niue"],
        ["Pacific/Norfolk", "Pacific/Norfolk"],
        ["Pacific/Noumea", "Pacific/Noumea"],
        ["Pacific/Pago_Pago", "Pacific/Pago_Pago"],
        ["Pacific/Palau", "Pacific/Palau"],
        ["Pacific/Pitcairn", "Pacific/Pitcairn"],
        ["Pacific/Pohnpei", "Pacific/Pohnpei"],
        ["Pacific/Ponape", "Pacific/Ponape"],
        ["Pacific/Port_Moresby", "Pacific/Port_Moresby"],
        ["Pacific/Rarotonga", "Pacific/Rarotonga"],
        ["Pacific/Saipan", "Pacific/Saipan"],
        ["Pacific/Samoa", "Pacific/Samoa"],
        ["Pacific/Tahiti", "Pacific/Tahiti"],
        ["Pacific/Tarawa", "Pacific/Tarawa"],
        ["Pacific/Tongatapu", "Pacific/Tongatapu"],
        ["Pacific/Truk", "Pacific/Truk"],
        ["Pacific/Wake", "Pacific/Wake"],
        ["Pacific/Wallis", "Pacific/Wallis"],
        ["Pacific/Yap", "Pacific/Yap"],
        ["Poland", "Poland"],
        ["Portugal", "Portugal"],
        ["ROC", "ROC"],
        ["ROK", "ROK"],
        ["Singapore", "Singapore"],
        ["Turkey", "Turkey"],
        ["UCT", "UCT"],
        ["US/Alaska", "US/Alaska"],
        ["US/Aleutian", "US/Aleutian"],
        ["US/Arizona", "US/Arizona"],
        ["US/Central", "US/Central"],
        ["US/East-Indiana", "US/East-Indiana"],
        ["US/Eastern", "US/Eastern"],
        ["US/Hawaii", "US/Hawaii"],
        ["US/Indiana-Starke", "US/Indiana-Starke"],
        ["US/Michigan", "US/Michigan"],
        ["US/Mountain", "US/Mountain"],
        ["US/Pacific", "US/Pacific"],
        ["US/Samoa", "US/Samoa"],
        ["UTC", "UTC"],
        ["Universal", "Universal"],
        ["W-SU", "W-SU"],
        ["WET", "WET"],
        ["Zulu", "Zulu"],
        ["Etc/GMT", "Etc/GMT"],
        ["Etc/GMT+0", "Etc/GMT+0"],
        ["Etc/GMT+1", "Etc/GMT+1"],
        ["Etc/GMT+10", "Etc/GMT+10"],
        ["Etc/GMT+11", "Etc/GMT+11"],
        ["Etc/GMT+12", "Etc/GMT+12"],
        ["Etc/GMT+2", "Etc/GMT+2"],
        ["Etc/GMT+3", "Etc/GMT+3"],
        ["Etc/GMT+4", "Etc/GMT+4"],
        ["Etc/GMT+5", "Etc/GMT+5"],
        ["Etc/GMT+6", "Etc/GMT+6"],
        ["Etc/GMT+7", "Etc/GMT+7"],
        ["Etc/GMT+8", "Etc/GMT+8"],
        ["Etc/GMT+9", "Etc/GMT+9"],
        ["Etc/GMT-0", "Etc/GMT-0"],
        ["Etc/GMT-1", "Etc/GMT-1"],
        ["Etc/GMT-10", "Etc/GMT-10"],
        ["Etc/GMT-11", "Etc/GMT-11"],
        ["Etc/GMT-12", "Etc/GMT-12"],
        ["Etc/GMT-13", "Etc/GMT-13"],
        ["Etc/GMT-14", "Etc/GMT-14"],
        ["Etc/GMT-2", "Etc/GMT-2"],
        ["Etc/GMT-3", "Etc/GMT-3"],
        ["Etc/GMT-4", "Etc/GMT-4"],
        ["Etc/GMT-5", "Etc/GMT-5"],
        ["Etc/GMT-6", "Etc/GMT-6"],
        ["Etc/GMT-7", "Etc/GMT-7"],
        ["Etc/GMT-8", "Etc/GMT-8"],
        ["Etc/GMT-9", "Etc/GMT-9"],
        ["Etc/GMT0", "Etc/GMT0"],
        ["Etc/Greenwich", "Etc/Greenwich"],
        ["Etc/UCT", "Etc/UCT"],
        ["Etc/UTC", "Etc/UTC"],
        ["Etc/Universal", "Etc/Universal"],
        ["Etc/Zulu", "Etc/Zulu"]
      ],
      sortable: true,
      store: true,
      string: "Timezone"
    },
    tz_offset: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["tz"],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Timezone offset",
      translate: false,
      trim: true
    },
    vat: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "The Tax Identification Number. Complete it if the contact is subjected to government taxes. Used in some legal statements.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Tax ID",
      translate: false,
      trim: true
    },
    same_vat_partner_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["vat", "company_id"],
      domain: [],
      manual: false,
      readonly: true,
      relation: "res.partner",
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Partner with same Tax ID"
    },
    bank_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.partner.bank",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Banks"
    },
    website: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Website Link",
      translate: false,
      trim: true
    },
    comment: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Notes",
      translate: false
    },
    category_id: {
      type: "many2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.partner.category",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Tags"
    },
    credit_limit: {
      type: "float",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Credit Limit"
    },
    active: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Active"
    },
    employee: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Check this box if this contact is an Employee.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Employee"
    },
    function: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Job Position",
      translate: false,
      trim: true
    },
    type: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Invoice & Delivery addresses are used in sales orders. Private addresses are only visible by authorized users.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [
        ["contact", "Contact"],
        ["invoice", "Invoice Address"],
        ["delivery", "Delivery Address"],
        ["other", "Other Address"],
        ["private", "Private Address"]
      ],
      sortable: true,
      store: true,
      string: "Address Type"
    },
    street: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Street",
      translate: false,
      trim: true
    },
    street2: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Street2",
      translate: false,
      trim: true
    },
    zip: {
      type: "char",
      change_default: true,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Zip",
      translate: false,
      trim: true
    },
    city: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "City",
      translate: false,
      trim: true
    },
    state_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: "[('country_id', '=?', country_id)]",
      manual: false,
      readonly: false,
      relation: "res.country.state",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "State"
    },
    country_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.country",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Country"
    },
    partner_latitude: {
      type: "float",
      change_default: false,
      company_dependent: false,
      depends: [],
      digits: [16, 5],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Geo Latitude"
    },
    partner_longitude: {
      type: "float",
      change_default: false,
      company_dependent: false,
      depends: [],
      digits: [16, 5],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Geo Longitude"
    },
    email_formatted: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["name", "email"],
      help: 'Format email address "Name <email@domain>"',
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Formatted Email",
      translate: false,
      trim: true
    },
    mobile: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Mobile",
      translate: false,
      trim: true
    },
    is_company: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Check if the contact is a company, otherwise it is a person",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Is a Company"
    },
    industry_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.partner.industry",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Industry"
    },
    company_type: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: ["is_company"],
      manual: false,
      readonly: false,
      required: false,
      searchable: false,
      selection: [
        ["person", "Individual"],
        ["company", "Company"]
      ],
      sortable: false,
      store: false,
      string: "Company Type"
    },
    company_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.company",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Company"
    },
    color: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Color Index"
    },
    user_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.users",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Users"
    },
    partner_share: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["user_ids.share", "user_ids.active"],
      help: "Either customer (not a user), either shared user. Indicated the current partner is a customer without access or with a limited access created for sharing data.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Share Partner"
    },
    contact_address: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [
        "street",
        "street2",
        "zip",
        "city",
        "state_id",
        "country_id",
        "city_id",
        "country_id",
        "company_name",
        "state_id"
      ],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Complete Address",
      translate: false,
      trim: true
    },
    commercial_partner_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["is_company", "parent_id.commercial_partner_id"],
      domain: [],
      manual: false,
      readonly: true,
      relation: "res.partner",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Commercial Entity"
    },
    commercial_company_name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["company_name", "parent_id.is_company", "commercial_partner_id.name"],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Company Name Entity",
      translate: false,
      trim: true
    },
    company_name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Company Name",
      translate: false,
      trim: true
    },
    barcode: {
      type: "char",
      change_default: false,
      company_dependent: true,
      depends: [],
      help: "Use a barcode to identify this contact.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Barcode",
      translate: false,
      trim: true
    },
    self: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "res.partner",
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Self"
    },
    signup_token: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      groups: "base.group_erp_manager",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Signup Token",
      translate: false,
      trim: true
    },
    signup_type: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      groups: "base.group_erp_manager",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Signup Token Type",
      translate: false,
      trim: true
    },
    signup_expiration: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: [],
      groups: "base.group_erp_manager",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Signup Expiration"
    },
    signup_valid: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["signup_token", "signup_expiration"],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Signup Token is Valid"
    },
    signup_url: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Signup URL",
      translate: false,
      trim: true
    },
    activity_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      groups: "base.group_user",
      manual: false,
      readonly: false,
      relation: "mail.activity",
      relation_field: "res_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Activities"
    },
    activity_state: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: ["activity_ids.state"],
      groups: "base.group_user",
      help: "Status based on activities\nOverdue: Due date is already passed\nToday: Activity date is today\nPlanned: Future activities.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      selection: [
        ["overdue", "Overdue"],
        ["today", "Today"],
        ["planned", "Planned"]
      ],
      sortable: false,
      store: false,
      string: "Activity State"
    },
    activity_user_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["activity_ids.user_id"],
      domain: [],
      groups: "base.group_user",
      manual: false,
      readonly: false,
      related: ["activity_ids", "user_id"],
      relation: "res.users",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Responsible User"
    },
    activity_type_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["activity_ids.activity_type_id"],
      domain: "['|', ('res_model_id', '=', False), ('res_model_id', '=', res_model_id)]",
      groups: "base.group_user",
      manual: false,
      readonly: false,
      related: ["activity_ids", "activity_type_id"],
      relation: "mail.activity.type",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Next Activity Type"
    },
    activity_type_icon: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["activity_ids.icon"],
      help: "Font awesome icon e.g. fa-tasks",
      manual: false,
      readonly: true,
      related: ["activity_ids", "icon"],
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Activity Type Icon",
      translate: false,
      trim: true
    },
    activity_date_deadline: {
      type: "date",
      change_default: false,
      company_dependent: false,
      depends: ["activity_ids.date_deadline"],
      groups: "base.group_user",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Next Activity Deadline"
    },
    my_activity_date_deadline: {
      type: "date",
      change_default: false,
      company_dependent: false,
      depends: ["activity_ids.date_deadline", "activity_ids.user_id"],
      groups: "base.group_user",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "My Activity Deadline"
    },
    activity_summary: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["activity_ids.summary"],
      groups: "base.group_user",
      manual: false,
      readonly: false,
      related: ["activity_ids", "summary"],
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Next Activity Summary",
      translate: false,
      trim: true
    },
    activity_exception_decoration: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [
        "activity_ids.activity_type_id.decoration_type",
        "activity_ids.activity_type_id.icon"
      ],
      help: "Type of the exception activity on record.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      selection: [
        ["warning", "Alert"],
        ["danger", "Error"]
      ],
      sortable: false,
      store: false,
      string: "Activity Exception Decoration"
    },
    activity_exception_icon: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [
        "activity_ids.activity_type_id.decoration_type",
        "activity_ids.activity_type_id.icon"
      ],
      help: "Icon to indicate an exception activity.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Icon",
      translate: false,
      trim: true
    },
    message_is_follower: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["message_follower_ids"],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Is Follower"
    },
    message_follower_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      groups: "base.group_user",
      manual: false,
      readonly: false,
      relation: "mail.followers",
      relation_field: "res_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Followers"
    },
    message_partner_ids: {
      type: "many2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["message_follower_ids"],
      domain: [],
      groups: "base.group_user",
      manual: false,
      readonly: true,
      relation: "res.partner",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Followers (Partners)"
    },
    message_channel_ids: {
      type: "many2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["message_follower_ids"],
      domain: [],
      groups: "base.group_user",
      manual: false,
      readonly: true,
      relation: "mail.channel",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Followers (Channels)"
    },
    message_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [["message_type", "!=", "user_notification"]],
      manual: false,
      readonly: false,
      relation: "mail.message",
      relation_field: "res_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Messages"
    },
    message_unread: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "If checked, new messages require your attention.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Unread Messages"
    },
    message_unread_counter: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      help: "Number of unread messages",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Unread Messages Counter"
    },
    message_needaction: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "If checked, new messages require your attention.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Action Needed"
    },
    message_needaction_counter: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      help: "Number of messages which requires an action",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Number of Actions"
    },
    message_has_error: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "If checked, some messages have a delivery error.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Message Delivery error"
    },
    message_has_error_counter: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      help: "Number of messages with delivery error",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Number of errors"
    },
    message_attachment_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      groups: "base.group_user",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Attachment Count"
    },
    message_main_attachment_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "ir.attachment",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Main Attachment"
    },
    email_normalized: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["email"],
      help: "This field is used to search on email address as the primary email field can contain more than strictly an email address.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Normalized Email",
      translate: false,
      trim: true
    },
    is_blacklisted: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["email_normalized"],
      groups: "base.group_user",
      help: "If the email address is on the blacklist, the contact won't receive mass mailing anymore, from any list",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Blacklist"
    },
    message_bounce: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      help: "Counter of the number of bounced emails for this contact",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Bounce"
    },
    im_status: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "IM Status",
      translate: false,
      trim: true
    },
    email: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Email",
      translate: false,
      trim: true
    },
    phone: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Phone",
      translate: false,
      trim: true
    },
    channel_ids: {
      type: "many2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "mail.channel",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Channels"
    },
    user_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      help: "The internal user in charge of this contact.",
      manual: false,
      readonly: false,
      relation: "res.users",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Salesperson"
    },
    website_message_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [
        ["model", "=", "res.partner"],
        "|",
        ["message_type", "=", "comment"],
        ["message_type", "=", "email"]
      ],
      help: "Website communication history",
      manual: false,
      readonly: false,
      relation: "mail.message",
      relation_field: "res_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Website Messages"
    },
    credit: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      help: "Total amount this customer owes you.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Total Receivable"
    },
    debit: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      help: "Total amount you have to pay to this vendor.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Total Payable"
    },
    debit_limit: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Payable Limit"
    },
    total_invoiced: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      groups: "account.group_account_invoice,account.group_account_readonly",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Total Invoiced"
    },
    currency_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      help: "Utility field to express amount currency",
      manual: false,
      readonly: true,
      relation: "res.currency",
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Currency"
    },
    journal_item_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Journal Items"
    },
    property_account_payable_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain:
        "[('internal_type', '=', 'payable'), ('deprecated', '=', False), ('company_id', '=', current_company_id)]",
      help: "This account will be used instead of the default one as the payable account for the current partner",
      manual: false,
      readonly: false,
      relation: "account.account",
      required: true,
      searchable: true,
      sortable: false,
      store: false,
      string: "Account Payable"
    },
    property_account_receivable_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain:
        "[('internal_type', '=', 'receivable'), ('deprecated', '=', False), ('company_id', '=', current_company_id)]",
      help: "This account will be used instead of the default one as the receivable account for the current partner",
      manual: false,
      readonly: false,
      relation: "account.account",
      required: true,
      searchable: true,
      sortable: false,
      store: false,
      string: "Account Receivable"
    },
    property_account_position_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain: "[('company_id', '=', current_company_id)]",
      help: "The fiscal position determines the taxes/accounts used for this contact.",
      manual: false,
      readonly: false,
      relation: "account.fiscal.position",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Fiscal Position"
    },
    property_payment_term_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain: "[('company_id', 'in', [current_company_id, False])]",
      help: "This payment term will be used instead of the default one for sales orders and customer invoices",
      manual: false,
      readonly: false,
      relation: "account.payment.term",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Customer Payment Terms"
    },
    property_supplier_payment_term_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain: "[('company_id', 'in', [current_company_id, False])]",
      help: "This payment term will be used instead of the default one for purchase orders and vendor bills",
      manual: false,
      readonly: false,
      relation: "account.payment.term",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Vendor Payment Terms"
    },
    ref_company_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.company",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Companies that refers to partner"
    },
    has_unreconciled_entries: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "The partner has at least one unreconciled debit and credit since last time the invoices & payments matching was performed.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Has Unreconciled Entries"
    },
    last_time_entries_checked: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: 'Last time the invoices & payments matching was performed for this partner. It is set either if there\'s not at least an unreconciled debit and an unreconciled credit or if you click the "Done" button.',
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Latest Invoices & Payments Matching Date"
    },
    invoice_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "account.move",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Invoices"
    },
    contract_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "account.analytic.account",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Partner Contracts"
    },
    bank_account_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Bank"
    },
    trust: {
      type: "selection",
      change_default: false,
      company_dependent: true,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [
        ["good", "Good Debtor"],
        ["normal", "Normal Debtor"],
        ["bad", "Bad Debtor"]
      ],
      sortable: false,
      store: false,
      string: "Degree of trust you have in this debtor"
    },
    invoice_warn: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: 'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.',
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [
        ["no-message", "No Message"],
        ["warning", "Warning"],
        ["block", "Blocking Message"]
      ],
      sortable: true,
      store: true,
      string: "Invoice"
    },
    invoice_warn_msg: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Message for Invoice",
      translate: false
    },
    supplier_rank: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Supplier Rank"
    },
    customer_rank: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Customer Rank"
    },
    contact_address_complete: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["street", "zip", "city", "country_id"],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Contact Address Complete",
      translate: false,
      trim: true
    },
    image_medium: {
      type: "binary",
      attachment: false,
      change_default: false,
      company_dependent: false,
      depends: ["image_128"],
      manual: false,
      readonly: true,
      related: ["image_128"],
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Medium-sized image"
    },
    phone_sanitized: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: ["country_id", "mobile", "phone"],
      help: "Field used to store sanitized phone number. Helps speeding up searches and comparisons.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Sanitized Number",
      translate: false,
      trim: true
    },
    phone_sanitized_blacklisted: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["phone_sanitized"],
      groups: "base.group_user",
      help: "If the sanitized phone number is on the blacklist, the contact won't receive mass mailing sms anymore, from any list",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Phone Blacklisted"
    },
    phone_blacklisted: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["phone_sanitized"],
      groups: "base.group_user",
      help: "Indicates if a blacklisted sanitized phone number is a phone number. Helps distinguish which number is blacklisted             when there is both a mobile and phone field in a model.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Blacklisted Phone is Phone"
    },
    mobile_blacklisted: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["phone_sanitized"],
      groups: "base.group_user",
      help: "Indicates if a blacklisted sanitized phone number is a mobile number. Helps distinguish which number is blacklisted             when there is both a mobile and phone field in a model.",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Blacklisted Phone Is Mobile"
    },
    ocn_token: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Used for sending notification to registered devices",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "OCN Token",
      translate: false,
      trim: true
    },
    partner_gid: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Company database ID"
    },
    additional_info: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Additional info",
      translate: false,
      trim: true
    },
    message_has_sms_error: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "If checked, some messages have a delivery error.",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "SMS Delivery error"
    },
    task_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "project.task",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Tasks"
    },
    task_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "# Tasks"
    },
    country_enforce_cities: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: ["country_id.enforce_cities"],
      help: "Check this box to ensure every address created in that country has a 'City' chosen in the list of the country's cities.",
      manual: false,
      readonly: true,
      related: ["country_id", "enforce_cities"],
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Enforce Cities"
    },
    city_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "res.city",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "City of Address"
    },
    calendar_last_notif_ack: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Last notification marked as read from base Calendar"
    },
    property_product_pricelist: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["country_id"],
      domain: [["company_id", "in", [1, false]]],
      help: "This pricelist will be used, instead of the default one, for sales to the current partner",
      manual: false,
      readonly: false,
      relation: "product.pricelist",
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Pricelist"
    },
    team_id: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      help: "If set, this Sales Team will be used for sales and assignments related to this partner",
      manual: false,
      readonly: false,
      relation: "crm.team",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Sales Team"
    },
    opportunity_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: ["opportunity_ids.type"],
      domain: [["type", "=", "opportunity"]],
      manual: false,
      readonly: false,
      relation: "crm.lead",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Opportunities"
    },
    meeting_ids: {
      type: "many2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "calendar.event",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Meetings"
    },
    opportunity_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Opportunity"
    },
    meeting_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "# Meetings"
    },
    online_partner_vendor_name: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Technical field used to store information from plaid/yodlee to match partner (used when a purchase is made)",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Online Partner Vendor Name",
      translate: false,
      trim: true
    },
    online_partner_bank_account: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Technical field used to store information from plaid/yodlee to match partner",
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Online Partner Bank Account",
      translate: false,
      trim: true
    },
    payment_token_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "payment.token",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Payment Tokens"
    },
    payment_token_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: ["payment_token_ids"],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Count Payment Token"
    },
    online_partner_information: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Online Partner Information",
      translate: false,
      trim: true
    },
    sale_order_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Sale Order Count"
    },
    sale_order_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: false,
      relation: "sale.order",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Sales Order"
    },
    sale_warn: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: 'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.',
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      selection: [
        ["no-message", "No Message"],
        ["warning", "Warning"],
        ["block", "Blocking Message"]
      ],
      sortable: true,
      store: true,
      string: "Sales Warnings"
    },
    sale_warn_msg: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Message for Sales Order",
      translate: false
    },
    payment_next_action_date: {
      type: "date",
      change_default: false,
      company_dependent: true,
      depends: [],
      help: "The date before which no action should be taken.",
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Next Action Date"
    },
    unreconciled_aml_ids: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [
        "unreconciled_aml_ids.reconciled",
        "unreconciled_aml_ids.account_id.deprecated",
        "unreconciled_aml_ids.account_id.internal_type",
        "unreconciled_aml_ids.move_id.state"
      ],
      domain: [
        ["reconciled", "=", false],
        ["account_id.deprecated", "=", false],
        ["account_id.internal_type", "=", "receivable"],
        ["move_id.state", "=", "posted"]
      ],
      manual: false,
      readonly: false,
      relation: "account.move.line",
      relation_field: "partner_id",
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Unreconciled Aml"
    },
    unpaid_invoices: {
      type: "one2many",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "account.move",
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Unpaid Invoices"
    },
    total_due: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Total Due"
    },
    total_overdue: {
      type: "monetary",
      change_default: false,
      company_dependent: false,
      currency_field: "currency_id",
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Total Overdue"
    },
    followup_status: {
      type: "selection",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      selection: [
        ["in_need_of_action", "In need of action"],
        ["with_overdue_invoices", "With overdue invoices"],
        ["no_action_needed", "No action needed"]
      ],
      sortable: false,
      store: false,
      string: "Follow-up Status"
    },
    followup_level: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "account_followup.followup.line",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Follow-up Level"
    },
    payment_responsible_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain: [],
      help: "Optionally you can assign a user to this field, which will make him responsible for the action.",
      manual: false,
      readonly: false,
      relation: "res.users",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Follow-up Responsible"
    },
    property_payment_method_id: {
      type: "many2one",
      change_default: false,
      company_dependent: true,
      context: {},
      depends: [],
      domain: "[('payment_type', '=', 'outbound')]",
      help: "Preferred payment method when paying this vendor. This is used to filter vendor bills by preferred payment method to register payments in mass. Use cases: create bank files for batch wires, check runs.",
      manual: false,
      readonly: false,
      relation: "account.payment.method",
      required: false,
      searchable: true,
      sortable: false,
      store: false,
      string: "Payment Method"
    },
    subscription_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Subscriptions"
    },
    l10n_ca_pst: {
      type: "char",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "PST",
      translate: false,
      trim: true
    },
    image_1920: {
      type: "binary",
      attachment: true,
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: false,
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Image"
    },
    image_1024: {
      type: "binary",
      attachment: true,
      change_default: false,
      company_dependent: false,
      depends: ["image_1920"],
      manual: false,
      readonly: true,
      related: ["image_1920"],
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Image 1024"
    },
    image_512: {
      type: "binary",
      attachment: true,
      change_default: false,
      company_dependent: false,
      depends: ["image_1920"],
      manual: false,
      readonly: true,
      related: ["image_1920"],
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Image 512"
    },
    image_256: {
      type: "binary",
      attachment: true,
      change_default: false,
      company_dependent: false,
      depends: ["image_1920"],
      manual: false,
      readonly: true,
      related: ["image_1920"],
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Image 256"
    },
    image_128: {
      type: "binary",
      attachment: true,
      change_default: false,
      company_dependent: false,
      depends: ["image_1920"],
      manual: false,
      readonly: true,
      related: ["image_1920"],
      required: false,
      searchable: true,
      sortable: false,
      store: true,
      string: "Image 128"
    },
    id: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "ID"
    },
    create_uid: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "res.users",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Created by"
    },
    create_date: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Created on"
    },
    write_uid: {
      type: "many2one",
      change_default: false,
      company_dependent: false,
      context: {},
      depends: [],
      domain: [],
      manual: false,
      readonly: true,
      relation: "res.users",
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Last Updated by"
    },
    write_date: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: false,
      readonly: true,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Last Updated on"
    },
    __last_update: {
      type: "datetime",
      change_default: false,
      company_dependent: false,
      depends: ["create_date", "write_date"],
      manual: false,
      readonly: true,
      required: false,
      searchable: false,
      sortable: false,
      store: false,
      string: "Last Modified on"
    },
    x_Test: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "Testing purpose",
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Test_Label",
      translate: false
    },
    x_themecolor: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Theme Color",
      translate: false
    },
    x_domainname: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Domain Name",
      translate: false
    },
    x_testcustom: {
      type: "boolean",
      change_default: false,
      company_dependent: false,
      depends: [],
      help: "just for testing ",
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Custom Test Field"
    },
    x_userlanguage: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "User Language",
      translate: false
    },
    x_collection_scroll_chart_count: {
      type: "integer",
      change_default: false,
      company_dependent: false,
      depends: [],
      group_operator: "sum",
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "collection_scroll_chart_count"
    },
    x_appname: {
      type: "text",
      change_default: false,
      company_dependent: false,
      depends: [],
      manual: true,
      readonly: false,
      required: false,
      searchable: true,
      sortable: true,
      store: true,
      string: "Application Name",
      translate: false
    }
  },
  errorDescription: ""
};
