import Head from "next/head";
import Image from "next/image";
import Todo from "@/components/Todo";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase/firebase";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import ContactForm from "@/components/ContactForm";

export default function Home() {
  const [user1, setUser] = useState();
  const router = useRouter();

  const getUser = async () =>
    await onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.push("/login");
        setUser(null);
      } else {
        setUser(user);
      }
    });

  useEffect(() => {
    getUser();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Todo user={user1}/> */}
      <ContactForm />
    </>
  );
}
